import os
from typing import List
from sqlalchemy.orm import Session
from sqlalchemy import func
from backend.database.sqlite_dal import (
    User,
    Subscription,
    QuizTopic,
    FlashcardTopic,
    EssayQATopic,
    TokenUsage,
    GenerationJob,
)


def is_admin_user(user: User) -> bool:
    """
    Check if a user is an admin.
    Admin emails are specified in ADMIN_EMAILS environment variable (comma-separated).
    """
    admin_emails_env = os.getenv("ADMIN_EMAILS", "")
    if not admin_emails_env:
        return False
    
    admin_emails = [email.strip().lower() for email in admin_emails_env.split(",") if email.strip()]
    return user.email.lower() in admin_emails


def get_user_account_type(user: User) -> str:
    """
    Determine if user is 'free' or 'pro' based on active subscriptions.
    Returns 'pro' if user has an active subscription, 'free' otherwise.
    """
    active_subscriptions = [
        sub for sub in user.subscriptions 
        if sub.status == "active"
    ]
    return "pro" if active_subscriptions else "free"


def get_user_quiz_count(db: Session, user_id: str) -> int:
    """
    Count the number of quizzes generated by a user.
    """
    return db.query(func.count(QuizTopic.id)).filter(
        QuizTopic.created_by_user_id == user_id
    ).scalar() or 0


def get_user_flashcard_count(db: Session, user_id: str) -> int:
    """
    Count the number of flashcard topics generated by a user.
    """
    return db.query(func.count(FlashcardTopic.id)).filter(
        FlashcardTopic.created_by_user_id == user_id
    ).scalar() or 0


def get_user_essay_count(db: Session, user_id: str) -> int:
    """
    Count the number of essay topics generated by a user.
    """
    return db.query(func.count(EssayQATopic.id)).filter(
        EssayQATopic.created_by_user_id == user_id
    ).scalar() or 0


def get_user_token_usage(db: Session, user_id: str) -> dict:
    """
    Get token usage statistics for a user.
    Returns a dictionary with input_tokens, output_tokens, and total_tokens.
    """
    # Get token usage from TokenUsage table (direct generations)
    token_usage_stats = db.query(
        func.sum(TokenUsage.input_tokens).label("input_tokens"),
        func.sum(TokenUsage.output_tokens).label("output_tokens"),
        func.sum(TokenUsage.total_tokens).label("total_tokens"),
    ).filter(
        TokenUsage.user_id == user_id
    ).first()
    
    # Get token usage from GenerationJob table (async jobs)
    job_token_stats = db.query(
        func.sum(GenerationJob.input_tokens).label("input_tokens"),
        func.sum(GenerationJob.output_tokens).label("output_tokens"),
        func.sum(GenerationJob.total_tokens).label("total_tokens"),
    ).filter(
        GenerationJob.user_id == user_id,
        GenerationJob.input_tokens.isnot(None)
    ).first()
    
    # Combine token statistics
    input_tokens = (token_usage_stats.input_tokens or 0) + (job_token_stats.input_tokens or 0)
    output_tokens = (token_usage_stats.output_tokens or 0) + (job_token_stats.output_tokens or 0)
    total_tokens = (token_usage_stats.total_tokens or 0) + (job_token_stats.total_tokens or 0)
    
    return {
        "input_tokens": int(input_tokens),
        "output_tokens": int(output_tokens),
        "total_tokens": int(total_tokens),
    }


def get_all_users_with_stats(db: Session) -> List[dict]:
    """
    Get all users with their account type and quiz counts.
    Returns a list of dictionaries with user information.
    """
    users = db.query(User).all()
    result = []
    
    for user in users:
        account_type = get_user_account_type(user)
        quiz_count = get_user_quiz_count(db, user.id)
        flashcard_count = get_user_flashcard_count(db, user.id)
        essay_count = get_user_essay_count(db, user.id)
        token_usage = get_user_token_usage(db, user.id)
        
        result.append({
            "id": user.id,
            "email": user.email,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "full_name": f"{user.first_name or ''} {user.last_name or ''}".strip() or None,
            "account_type": account_type,
            "quiz_count": quiz_count,
            "flashcard_count": flashcard_count,
            "essay_count": essay_count,
            "is_active": user.is_active,
            "created_at": user.created_at.isoformat() if user.created_at else None,
            "free_tokens": user.free_tokens,
            "input_tokens": token_usage["input_tokens"],
            "output_tokens": token_usage["output_tokens"],
            "total_tokens": token_usage["total_tokens"],
        })
    
    return result

