import os
from typing import List
from sqlalchemy.orm import Session
from sqlalchemy import func
from backend.database.sqlite_dal import User, Subscription, QuizTopic


def is_admin_user(user: User) -> bool:
    """
    Check if a user is an admin.
    Admin emails are specified in ADMIN_EMAILS environment variable (comma-separated).
    """
    admin_emails_env = os.getenv("ADMIN_EMAILS", "")
    if not admin_emails_env:
        return False
    
    admin_emails = [email.strip().lower() for email in admin_emails_env.split(",") if email.strip()]
    return user.email.lower() in admin_emails


def get_user_account_type(user: User) -> str:
    """
    Determine if user is 'free' or 'pro' based on active subscriptions.
    Returns 'pro' if user has an active subscription, 'free' otherwise.
    """
    active_subscriptions = [
        sub for sub in user.subscriptions 
        if sub.status == "active"
    ]
    return "pro" if active_subscriptions else "free"


def get_user_quiz_count(db: Session, user_id: str) -> int:
    """
    Count the number of quizzes generated by a user.
    """
    return db.query(func.count(QuizTopic.id)).filter(
        QuizTopic.created_by_user_id == user_id
    ).scalar() or 0


def get_all_users_with_stats(db: Session) -> List[dict]:
    """
    Get all users with their account type and quiz counts.
    Returns a list of dictionaries with user information.
    """
    users = db.query(User).all()
    result = []
    
    for user in users:
        account_type = get_user_account_type(user)
        quiz_count = get_user_quiz_count(db, user.id)
        
        result.append({
            "id": user.id,
            "email": user.email,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "full_name": f"{user.first_name or ''} {user.last_name or ''}".strip() or None,
            "account_type": account_type,
            "quiz_count": quiz_count,
            "is_active": user.is_active,
            "created_at": user.created_at.isoformat() if user.created_at else None,
            "free_tokens": user.free_tokens,
        })
    
    return result

